[package]
name = "rust-t9"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.3", features = ["derive"] }
str-distance = "0.1.0"
triple_accel = "0.4.0"
